### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by jschaeff** [EIDA/eida-statistics#11]

**Comment by jschaeff** [comment]
I updated the openAPI specifications:

- review of the descriptions
- change of the server / URL
- adding a _nodes method to get list of nodes (needs to be implemented)
- set `datacenter` parameter as an array, which enum values are among the /_nodes result (need to be finished)


@vpet98 could you:
- look at the best way to generate the documentation of the webservice directly ? Like for exemple with https://pypi.org/project/openapi-ui-bundles/
- finish the work on the API description by adding default values, specifying when multiple values are possible (look at the openapi spec)
- implement _nodes method
- rename health to _health
- enable '*' wildcard on Net/Sta/Loc/Cha selection parametes
- datacenters : set '*' as default value or put in description that empty means all datacenters.

**Comment by vpet98** [comment]
The way it is implemented, leaving for example station field empty means all stations, like in fdsn webservice. Shall I change this so that leaving station empty means a default station e.g. CIEL? The '*' wildcards are enabled.

Also, shall I add a format parameter at /dataselect/stat method as you added at specs?
