### ISSUE TITLE
Reimplementation with a better framework

### ISSUE THREAD

**Issue by jschaeff** [EIDA/eida-statistics#22]
- tightly link the implementation, the openapi definition and the documentation
- document the code
- separate code in an MVC framework

**Comment by vpet98** [comment]
I finished with moving to pyramid framework and also added more logging in my code. It's uploaded in a dev_pyramid branch.

Regarding the documentation, I didn't find any tool that can generate it from the implementation without writing some openapi specs code at some point. I used [https://github.com/Pylons/pyramid_openapi3](https://github.com/Pylons/pyramid_openapi3) that validates the views against the yaml file when application is running and thus forcing implementation and documentation to comply with each other. The pyramid-openapi3 package also provides a way to view the ducumentation with Swagger UI and I used it so that documentation appears in the root URL of the app (it definitely works for localhost, I hope this time it works for .../statistics/1 path as well, since I cannot test it on my own).

I have removed my old ducumentation pages for now, but maybe it is a good idea to add them too, since they can offer more functionality (e.g. autocomplete function for datacenter).

Note also that I had to make some changes in the Dockerfile to support pyramid framework applications. While it works now, it is possible that I didn't modified it the best way, so I think it's better to have a look at it.
