### ISSUE TITLE
empty stats for GFZ

### ISSUE THREAD

**Issue by KlausStammler** [EIDA/eida-statistics#23]
Thanks for publishing this interface. When retrieving yearly network statistics for each node I get results for all nodes except GFZ:

https://ws.resif.fr/eidaws/statistics/1/dataselect/query?start=2022-01&end=2022-12&datacenter=GFZ&aggregate_on=month,station,country&format=json

returns an empty result. The same happens with unknown data center names. Better would be to return an error if the data center name is invalid.

I also tried "../submit/.." instead of "../dataselect/..". This doesn't work at all.

**Comment by vpet98** [comment]
Hello,

Thank you for the feedback. The GFZ datacenter exists in the database under the name GEOFON, so that is the one you need to use in your query. Returning an error if datacenter name is invalid seems a good idea, it can be implemented in the next update.

The ".../submit" method only accepts POST or PUT requests with a JSON file as parameter and is only for ingesting statistics into the database.
